In [3]:
import numpy as np

In [11]:
#Arrays de 3 dimensões
arr_3d = np.array([
    [
        [x for x in range(4)], 
        [x for x in range(4,8)], 
        [x for x in range(8,12)],
    ],
    [
        [x for x in range(12,16)], 
        [x for x in range(16,20)], 
        [x for x in range(20,24)],
    ]])
arr_3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
#Numero de dimensoes de um array
arr_3d.ndim

3

In [15]:
#Retorna a forma do array, nesse caso, possui 2 elementos listas, cada um com 3 listas e cada lista com 4 elementos
arr_3d.shape

(2, 3, 4)

In [17]:
#Pegando um item do array
arr_3d[0, 2, 3]

np.int64(11)

In [23]:
arr = np.array([x for x in range(1,101)])
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
#Calcula a média do array
arr.mean()

#Outra forma
np.mean(arr)

np.float64(50.5)

In [28]:
#Calculo do desvio padrao
arr.std()

#Outra forma
np.std(arr)

np.float64(28.86607004772212)

In [31]:
#Calculando a variancia
arr.var()

#Outra forma
np.var(arr)

np.float64(833.25)

In [ ]:
arr1 = np.array([x for x in range(0,10)])
arr2 = np.array([x for x in range(11,21)])

In [37]:
#Soma
arr12 = np.add(arr1, arr2)
arr12

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29])